insert into shop.tags (tag_name) values ('NIGHTTIME SLEEP AID');
insert into shop.tags (tag_name) values ('Testosterone Cypionate');
insert into shop.tags (tag_name) values ('Vinorelbine');
insert into shop.tags (tag_name) values ('DIDANOSINE');
insert into shop.tags (tag_name) values ('Benicar');
insert into shop.tags (tag_name) values ('IASO INTENSIVE CLEAR CONDITIONER');
insert into shop.tags (tag_name) values ('Mucinex Fast-Max Night Time Cold and Flu');
insert into shop.tags (tag_name) values ('Nitrogen');
insert into shop.tags (tag_name) values ('Cetirizine Hydrochloride');
insert into shop.tags (tag_name) values ('Botanics Daily Hand Therapy Sunscreen SPF 10');
insert into shop.tags (tag_name) values ('CEFADROXIL');
insert into shop.tags (tag_name) values ('Portia');
insert into shop.tags (tag_name) values ('Estradiol');
insert into shop.tags (tag_name) values ('Doxepin Hydrochloride');
insert into shop.tags (tag_name) values ('STEMPHYLIUM SOLANI');
insert into shop.tags (tag_name) values ('Halls');
insert into shop.tags (tag_name) values ('Molds, Rusts and Smuts, Fusarium vasinfectum');
insert into shop.tags (tag_name) values ('Morphine Sulfate');
insert into shop.tags (tag_name) values ('Clindagel');
insert into shop.tags (tag_name) values ('DOBUTamine Hydrochloride in Dextrose');
insert into shop.tags (tag_name) values ('Hydrocodone Bitartrate And Acetaminophen');
insert into shop.tags (tag_name) values ('Delsym');
insert into shop.tags (tag_name) values ('RAYOS');
insert into shop.tags (tag_name) values ('Codituss DM');
insert into shop.tags (tag_name) values ('Olay Total Effects CC Tone Correcting');
insert into shop.tags (tag_name) values ('NIGROSPORA SPHAERICA');
insert into shop.tags (tag_name) values ('CLARINS SPF 15 Sunscreen');
insert into shop.tags (tag_name) values ('Topical Fluoride Foam Bumble Bee Bubble Gum');
insert into shop.tags (tag_name) values ('Hand Wash');
insert into shop.tags (tag_name) values ('Dove');
insert into shop.tags (tag_name) values ('Prandin');
insert into shop.tags (tag_name) values ('Capzasin No Mess Applicator');
insert into shop.tags (tag_name) values ('Compazine');
insert into shop.tags (tag_name) values ('LE TECHNIQ');
insert into shop.tags (tag_name) values ('shoprite allergy and congestion relief');
insert into shop.tags (tag_name) values ('SHISEIDO FOUNDATION (Refill)');
insert into shop.tags (tag_name) values ('Vancomycin Hydrochloride');
insert into shop.tags (tag_name) values ('Rohto Relief');
insert into shop.tags (tag_name) values ('CVS Medicated Chest Rub Roll-On');
insert into shop.tags (tag_name) values ('White Spruce Hand Sanitizer');
insert into shop.tags (tag_name) values ('Dicyclomine Hydrochloride');
insert into shop.tags (tag_name) values ('Cryselle');
insert into shop.tags (tag_name) values ('ESIKA');
insert into shop.tags (tag_name) values ('Treatment Set TS333635');
insert into shop.tags (tag_name) values ('Buttermilk Time Frame Future Resist');
insert into shop.tags (tag_name) values ('AntiBac Foam Wash');
insert into shop.tags (tag_name) values ('Bupropion Hydrochloride');
insert into shop.tags (tag_name) values ('MORUS ALBA POLLEN');
insert into shop.tags (tag_name) values ('modafinil');
insert into shop.tags (tag_name) values ('SHISEIDO RADIANT LIFTING FOUNDATION');
insert into shop.tags (tag_name) values ('Alendronate Sodium');
insert into shop.tags (tag_name) values ('Advanced Healing');
insert into shop.tags (tag_name) values ('Hydroxychloroquine sulfate');
insert into shop.tags (tag_name) values ('Klor-Con');
insert into shop.tags (tag_name) values ('Metoprolol Tartrate');
insert into shop.tags (tag_name) values ('Etodolac');
insert into shop.tags (tag_name) values ('Loratadine and Pseudoephedrine Sulfate');
insert into shop.tags (tag_name) values ('Felodipine');
insert into shop.tags (tag_name) values ('PROMETHAZINE DM');
insert into shop.tags (tag_name) values ('Pure Finish Mineral');
insert into shop.tags (tag_name) values ('Zcaine Fast Acting Anesthetic');
insert into shop.tags (tag_name) values ('Ipratropium Bromide and Albuterol Sulfate');
insert into shop.tags (tag_name) values ('Phenytoin Sodium');
insert into shop.tags (tag_name) values ('topcare cold');
insert into shop.tags (tag_name) values ('Clonidine Hydrochloride');
insert into shop.tags (tag_name) values ('Benazepril Hydrochloride');
insert into shop.tags (tag_name) values ('Ultracruz Antibacterial');
insert into shop.tags (tag_name) values ('Lisinopril and Hydrochlorothiazide');
insert into shop.tags (tag_name) values ('Dove');
insert into shop.tags (tag_name) values ('Oxygen');
insert into shop.tags (tag_name) values ('ACTIMMUNE');
insert into shop.tags (tag_name) values ('Hog Epithelium');
insert into shop.tags (tag_name) values ('JAPANESE CHERRY BLOSSOM');
insert into shop.tags (tag_name) values ('Lamotrigine');
insert into shop.tags (tag_name) values ('Heparin Sodium');
insert into shop.tags (tag_name) values ('Chlordiazepoxide Hydrochloride');
insert into shop.tags (tag_name) values ('CLE DE PEAU BEAUTE PW FOUNDATION s');
insert into shop.tags (tag_name) values ('Rite Aid Ultimate Sheer');
insert into shop.tags (tag_name) values ('Tramadol Hydrochloride');
insert into shop.tags (tag_name) values ('Levobunolol Hydrochloride');
insert into shop.tags (tag_name) values ('Suave');
insert into shop.tags (tag_name) values ('Ray Defense');
insert into shop.tags (tag_name) values ('hydrocortisone');
insert into shop.tags (tag_name) values ('risperidone');
insert into shop.tags (tag_name) values ('Sulfur Cleanser');
insert into shop.tags (tag_name) values ('Antibacterial Gold');
insert into shop.tags (tag_name) values ('Carvedilol');
insert into shop.tags (tag_name) values ('womans laxative');
insert into shop.tags (tag_name) values ('Metformin Hydrochloride');
insert into shop.tags (tag_name) values ('Ethambutol Hydrochloride');
insert into shop.tags (tag_name) values ('Primidone');
insert into shop.tags (tag_name) values ('Premarin');
insert into shop.tags (tag_name) values ('Purminerals 4 in 1 Makeup');
insert into shop.tags (tag_name) values ('Triamcinolone Acetonide');
insert into shop.tags (tag_name) values ('Prednisone');
insert into shop.tags (tag_name) values ('oxycodone hydrochloride');
insert into shop.tags (tag_name) values ('CLADOSPORIUM SPHAEROSPERMUM');
insert into shop.tags (tag_name) values ('Polyethylene Glycol 3350');
insert into shop.tags (tag_name) values ('Chlordiazepoxide Hydrochloride');
insert into shop.tags (tag_name) values ( 'Clean Choice Alcohol Sanitizer');

insert into shop.book2tag (book_id, tag_id) values (7, 31);
insert into shop.book2tag (book_id, tag_id) values (9, 8);
insert into shop.book2tag (book_id, tag_id) values (1, 9);
insert into shop.book2tag (book_id, tag_id) values (8, 6);
insert into shop.book2tag (book_id, tag_id) values (7, 3);
insert into shop.book2tag (book_id, tag_id) values (1, 1);
insert into shop.book2tag (book_id, tag_id) values (2, 18);
insert into shop.book2tag (book_id, tag_id) values (106, 17);
insert into shop.book2tag (book_id, tag_id) values (6, 22);
insert into shop.book2tag (book_id, tag_id) values (95, 6);
insert into shop.book2tag (book_id, tag_id) values (37, 2);
insert into shop.book2tag (book_id, tag_id) values (79, 3);
insert into shop.book2tag (book_id, tag_id) values (57, 4);
insert into shop.book2tag (book_id, tag_id) values (42, 4);
insert into shop.book2tag (book_id, tag_id) values (66, 5);
insert into shop.book2tag (book_id, tag_id) values (23, 6);
insert into shop.book2tag (book_id, tag_id) values (68, 7);
insert into shop.book2tag (book_id, tag_id) values (8, 8);
insert into shop.book2tag (book_id, tag_id) values (15, 9);
insert into shop.book2tag (book_id, tag_id) values (14, 10);
insert into shop.book2tag (book_id, tag_id) values (3, 11);
insert into shop.book2tag (book_id, tag_id) values (10, 12);
insert into shop.book2tag (book_id, tag_id) values (5, 14);
insert into shop.book2tag (book_id, tag_id) values (76, 5);
insert into shop.book2tag (book_id, tag_id) values (62, 9);
insert into shop.book2tag (book_id, tag_id) values (85, 5);
insert into shop.book2tag (book_id, tag_id) values (84, 8);
insert into shop.book2tag (book_id, tag_id) values (59, 5);
insert into shop.book2tag (book_id, tag_id) values (62, 3);
insert into shop.book2tag (book_id, tag_id) values (71, 20);
insert into shop.book2tag (book_id, tag_id) values (13, 9);
insert into shop.book2tag (book_id, tag_id) values (60, 22);
insert into shop.book2tag (book_id, tag_id) values (47, 23);
insert into shop.book2tag (book_id, tag_id) values (34, 24);
insert into shop.book2tag (book_id, tag_id) values (84, 1);
insert into shop.book2tag (book_id, tag_id) values (25, 2);
insert into shop.book2tag (book_id, tag_id) values (58, 10);
insert into shop.book2tag (book_id, tag_id) values (6, 28);
insert into shop.book2tag (book_id, tag_id) values (97, 23);
insert into shop.book2tag (book_id, tag_id) values (47, 22);
insert into shop.book2tag (book_id, tag_id) values (95, 1);
insert into shop.book2tag (book_id, tag_id) values (100, 25);
insert into shop.book2tag (book_id, tag_id) values (59, 29);
insert into shop.book2tag (book_id, tag_id) values (71, 27);
insert into shop.book2tag (book_id, tag_id) values (64, 28);
insert into shop.book2tag (book_id, tag_id) values (53, 22);
insert into shop.book2tag (book_id, tag_id) values (57, 27);
insert into shop.book2tag (book_id, tag_id) values (64, 29);
insert into shop.book2tag (book_id, tag_id) values (9, 9);
insert into shop.book2tag (book_id, tag_id) values (24, 21);
insert into shop.book2tag (book_id, tag_id) values (6, 12);
insert into shop.book2tag (book_id, tag_id) values (66, 29);
insert into shop.book2tag (book_id, tag_id) values (9, 12);
insert into shop.book2tag (book_id, tag_id) values (53, 9);
insert into shop.book2tag (book_id, tag_id) values (64, 30);
insert into shop.book2tag (book_id, tag_id) values (24, 15);
insert into shop.book2tag (book_id, tag_id) values (4, 9);
insert into shop.book2tag (book_id, tag_id) values (15, 7);
insert into shop.book2tag (book_id, tag_id) values (33, 14);
insert into shop.book2tag (book_id, tag_id) values (46, 10);
insert into shop.book2tag (book_id, tag_id) values (82, 10);
insert into shop.book2tag (book_id, tag_id) values (30, 16);
insert into shop.book2tag (book_id, tag_id) values (53, 5);
insert into shop.book2tag (book_id, tag_id) values (41, 10);
insert into shop.book2tag (book_id, tag_id) values (69, 19);
insert into shop.book2tag (book_id, tag_id) values (90, 16);
insert into shop.book2tag (book_id, tag_id) values (69, 15);
insert into shop.book2tag (book_id, tag_id) values (5, 16);
insert into shop.book2tag (book_id, tag_id) values (71, 15);
insert into shop.book2tag (book_id, tag_id) values (77, 31);
insert into shop.book2tag (book_id, tag_id) values (19, 14);
insert into shop.book2tag (book_id, tag_id) values (80, 12);
insert into shop.book2tag (book_id, tag_id) values (52, 8);
insert into shop.book2tag (book_id, tag_id) values (90, 15);
insert into shop.book2tag (book_id, tag_id) values (54, 17);
insert into shop.book2tag (book_id, tag_id) values (69, 29);
insert into shop.book2tag (book_id, tag_id) values (2, 29);
insert into shop.book2tag (book_id, tag_id) values (800, 16);
insert into shop.book2tag (book_id, tag_id) values (300, 17);
insert into shop.book2tag (book_id, tag_id) values (260, 23);
insert into shop.book2tag (book_id, tag_id) values (940, 28);
insert into shop.book2tag (book_id, tag_id) values (460, 26);
insert into shop.book2tag (book_id, tag_id) values (850, 13);
insert into shop.book2tag (book_id, tag_id) values (210, 7);
insert into shop.book2tag (book_id, tag_id) values (70, 31);
insert into shop.book2tag (book_id, tag_id) values (350, 31);
insert into shop.book2tag (book_id, tag_id) values (20, 30);
insert into shop.book2tag (book_id, tag_id) values (870, 3);
insert into shop.book2tag (book_id, tag_id) values (290, 2);
insert into shop.book2tag (book_id, tag_id) values (540, 3);
insert into shop.book2tag (book_id, tag_id) values (560, 9);
insert into shop.book2tag (book_id, tag_id) values (720, 24);
insert into shop.book2tag (book_id, tag_id) values (320, 7);
insert into shop.book2tag (book_id, tag_id) values (660, 3);
insert into shop.book2tag (book_id, tag_id) values (980, 1);
insert into shop.book2tag (book_id, tag_id) values (170, 5);
insert into shop.book2tag (book_id, tag_id) values (790, 4);
insert into shop.book2tag (book_id, tag_id) values (460, 8);
insert into shop.book2tag (book_id, tag_id) values (960, 2);
insert into shop.book2tag (book_id, tag_id) values (480, 6);
